# Generated by Django 4.2.23 on 2026-02-06 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_filed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
